# Generated by Django 5.1.3 on 2024-11-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0002_remove_cart_combo_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comboproduct',
            old_name='quantity_combo',
            new_name='quantity_products',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ru',
        ),
        migrations.RemoveField(
            model_name='store',
            name='description_store_en',
        ),
        migrations.RemoveField(
            model_name='store',
            name='description_store_ky',
        ),
        migrations.RemoveField(
            model_name='store',
            name='description_store_ru',
        ),
    ]
