# Generated by Django 5.1.3 on 2024-11-22 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0003_rename_quantity_combo_comboproduct_quantity_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboproduct',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_site.combo'),
        ),
    ]
