# Generated by Django 5.1.3 on 2024-11-22 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0006_alter_cartitem_combo_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courier_order', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('ожидания', 'ожидания'), ('В процессе  доставки.', 'В процессе доставки.'), ('доставлено', 'доставлено'), ('Отменен', 'Отменен')], default='ожидания', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
