# Generated by Django 5.1.3 on 2024-11-19 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0008_rename_quantity_comboproduct_quantity_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='cart_courier',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='status_courier',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glovo_site.cart')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='glovo_site.courier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
