# Generated by Django 5.1.3 on 2024-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0009_remove_courier_cart_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
