# Generated by Django 5.1.3 on 2024-11-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0010_review_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='courier',
            new_name='courier_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='store',
            new_name='store_rating',
        ),
    ]
