# Generated by Django 5.1.3 on 2024-11-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0011_rename_courier_review_courier_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.AddField(
            model_name='courier',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glovo_site.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status_book',
            field=models.CharField(choices=[('ожидания', 'ожидания'), ('в пути', 'в пути'), ('доставлено', 'доставлено')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
