# Generated by Django 5.1.3 on 2024-11-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_site', '0012_remove_order_courier_courier_order_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_site.combo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_site.product'),
        ),
    ]
